name: 'SW - Build System and Package Manager'
description: 'Setup and prepare SW tool'
author: 'Egor Pugin'

branding:
  icon: 'box'
  color: 'blue'
  
steps:
  - name: Download SW
    shell: cmake -P {0}
    run: |
      file(DOWNLOAD "https://software-network.org/client/sw-master-windows-client.zip" ./sw.zip SHOW_PROGRESS)

  - name: Unpack SW
    run: cmake -E tar xvf sw.zip
